export const routes = {
    "user_profile": "/user/profile",
    "user_dashboard": "/user/dashboard",
    "user_purchase_history": "/user/purchase_history",
    "user_purchase_details": "/user/purchase_history/details",
    "user_wish_list": "/user/wish_list",
    "user_address": "/user/address",
    "user_address_add": "/user/address/add",
    "user_address_edit": "/user/address/edit",
    "track_order": "/track-order",
    "rewards": "/rewards",
    "user_earning_points": "/user/earning-points",
    "user_affiliate": "/user/affiliate",
    "payment_history": "/user/affiliate/payment_history",
    "withdraw_request_history": "/user/affiliate/withdraw_request_history",
    "payment_settings": "/user/affiliate/payment/settings",
    "withdraw": "/user/affiliate/withdraw",
}
export const routes_with_out_slash = {
    "user_profile": "user/profile",
    "user_dashboard": "user/dashboard",
    "user_purchase_history": "user/purchase_history",
    "user_purchase_details": "user/purchase_history/details",
    "user_wish_list": "user/wish_list",
    "user_address": "user/address",
    "user_address_add": "user/address/add",
    "user_address_edit": "user/address/edit",
    "track_order": "track-order",
    "rewards": "rewards",
    "user_earning_points": "user/earning-points",
    "user_affiliate": "user/affiliate",
}